# Generated by Django 4.2.7 on 2023-11-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label_word_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.CreateModel(
            name='LabelledText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_word_backend.document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_word_backend.label')),
            ],
        ),
    ]
